# Generated by Django 2.1.7 on 2019-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190324_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='2019-05-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Omaha', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2019-05-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Hummel Park', max_length=200),
            preserve_default=False,
        ),
    ]
