# Generated by Django 2.1.7 on 2019-03-31 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190331_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='higher_age_range',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(125)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='lower_age_range',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(125)]),
        ),
    ]
