# Generated by Django 2.1.7 on 2019-04-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190331_1001'),
        ('app', '0012_auto_20190331_1015'),
    ]

    operations = [
    ]
