# Generated by Django 2.1.7 on 2019-03-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
