# Generated by Django 2.1.7 on 2019-04-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190331_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parent_user',
            new_name='parent_id',
        ),
    ]
