# Generated by Django 2.1.7 on 2019-04-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20190401_2216'),
        ('app', '0017_auto_20190402_0903'),
    ]

    operations = [
    ]
