# Generated by Django 2.1.7 on 2019-04-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20190401_2121'),
        ('app', '0018_merge_20190402_0919'),
    ]

    operations = [
    ]
