# Generated by Django 2.1.7 on 2019-04-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20190403_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='PKI S 69th st', max_length=200),
            preserve_default=False,
        ),
    ]
