# Generated by Django 2.1.7 on 2019-04-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_event_address'),
        ('app', '0021_auto_20190406_1355'),
    ]

    operations = [
    ]
