# Generated by Django 2.1.7 on 2019-04-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userloginactivity'),
        ('app', '0025_auto_20190415_2040'),
    ]

    operations = [
    ]
