# Generated by Django 2.1.7 on 2019-04-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_user_approved_to_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='approved_to_post',
            new_name='approved_to_post_events',
        ),
    ]
