version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=stem_ecosystem
      - POSTGRES_USER=stem_admin
      - POSTGRES_PASSWORD=${STEM_PSQL_PASSWORD}

  django:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata initial_data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - STEM_SECRET_KEY=${STEM_SECRET_KEY}
      - STEM_PSQL_PASSWORD=${STEM_PSQL_PASSWORD}
      - DOCKER_SETUP_FLAG=TRUE

  angular:
    build:
      context: ./src
      dockerfile: ./Dockerfile.Web
    restart: always
    working_dir: /app/frontend
    command: bash -c "ng serve --poll=2000 --host 0.0.0.0"
    volumes:
      - ./src:/app
      - /app/frontend/node_modules
      - /home/node/.npm-global
    ports:
      - "4200:4200"
