# Generated by Django 2.1.7 on 2019-02-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190218_1924'),
        ('app', '0003_remove_user_student'),
    ]

    operations = [
    ]
