# Generated by Django 2.1.7 on 2019-03-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190302_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='e_type',
        ),
    ]
