import { User } from './user';

export const USERS: any = [
  {
    username: 'root',
    email: 'stem-ecosystem-root@unomaha.edu',
    first_name: 'Stem',
    last_name: 'Ecosystem',
    date_of_birth: '1990-01-01',
    organization: null,
    user_type: 4,
    is_student: false,
  },
  {
    username: 'michaelscott',
    email: 'michael.scott@dunder-mifflin.com',
    first_name: 'Michael',
    last_name: 'Scott',
    date_of_birth: '1964-03-15',
    organization: 1,
    user_type: 3,
    is_student: false,
  },
  {
    username: 'pambeesly',
    email: 'pam.beesly@dunder-mifflin.com',
    first_name: 'Pam',
    last_name: 'Beesly',
    date_of_birth: '1979-03-25',
    organization: null,
    user_type: 1,
    is_student: true,
  },
  {
    username: 'tobyflenderson',
    email: 'toby.flenderson@dunder-mifflin.com',
    first_name: 'Toby',
    last_name: 'Flenderson',
    date_of_birth: '1971-11-14',
    organization: null,
    user_type: 3,
    is_student: false,
  },
  {
    username: 'dwightschrute',
    email: 'dwight.schrute@dunder-mifflin.com',
    first_name: 'Dwight',
    last_name: 'Schrute',
    date_of_birth: '1972-01-20',
    organization: 2,
    user_type: 4,
    is_student: false,
  },
  {
    username: 'jimhalpert',
    email: 'jim.halpert@dunder-mifflin.com',
    first_name: 'Jim',
    last_name: 'Halpert',
    date_of_birth: '1978-10-01',
    organization: null,
    user_type: 2,
    is_student: false,
  },
  {
    username: 'andybernard',
    email: 'andy.bernard@dunder-mifflin.com',
    first_name: 'Andy',
    last_name: 'Bernard',
    date_of_birth: '1973-08-12',
    organization: null,
    user_type: 1,
    is_student: true,
  },
  {
    username: 'kevinmalone',
    email: 'kevin.malone@dunder-mifflin.com',
    first_name: 'Kevin',
    last_name: 'Malone',
    date_of_birth: '1968-06-01',
    organization: null,
    user_type: 1,
    is_student: true,
  },
  {
    username: 'angelamartin',
    email: 'angela.martin@dunder-mifflin.com',
    first_name: 'Angela',
    last_name: 'Martin',
    date_of_birth: '1970-04-22',
    organization: null,
    user_type: 3,
    is_student: false,
  },
  {
    username: 'stanleyhudson',
    email: 'stanley.hudson@dunder-mifflin.com',
    first_name: 'Stanley',
    last_name: 'Hudson',
    date_of_birth: '1960-08-17',
    organization: null,
    user_type: 2,
    is_student: false,
  },
  {
    username: 'creedbratton',
    email: 'creed.bratton@dunder-mifflin.com',
    first_name: 'Creed',
    last_name: 'Bratton',
    date_of_birth: '1943-02-08',
    organization: null,
    user_type: 2,
    is_student: false,
  },
  {
    username: 'ryanhoward',
    email: 'ryan.howard@dunder-mifflin.com',
    first_name: 'Ryan',
    last_name: 'Howard',
    date_of_birth: '1979-05-05',
    organization: null,
    user_type: 3,
    is_student: false,
  },
  {
    username: 'kellykapoor',
    email: 'kelly.kapoor@dunder-mifflin.com',
    first_name: 'Kelly',
    last_name: 'Kapoor',
    date_of_birth: '1980-02-05',
    organization: null,
    user_type: 1,
    is_student: true,
  },
  {
    username: 'meredithpalmer',
    email: 'meredith.palmer@dunder-mifflin.com',
    first_name: 'Meredith',
    last_name: 'Palmer',
    date_of_birth: '1959-05-12',
    organization: null,
    user_type: 2,
    is_student: false,
  },
  {
    username: 'darrylphilbin',
    email: 'darryl.philbin@dunder-mifflin.com',
    first_name: 'Darryl',
    last_name: 'Philbin',
    date_of_birth: '1979-10-02',
    organization: null,
    user_type: 1,
    is_student: true,
  },
  {
    username: 'phyllisvance',
    email: 'phyllis.vance@dunder-mifflin.com',
    first_name: 'Phyllis',
    last_name: 'Vance',
    date_of_birth: '1972-08-23',
    organization: null,
    user_type: 3,
    is_student: false,
  },
];
